import "./globals.css";
import Navbar from '@/Components/Navbar'

export const metadata = {
  title: "Electrodomesticos Capellari",
  description: "Generated by Cecilia Perdomo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        </body>
    </html>
  );
}
